# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [3]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
arr1.shape, arr1.ndim, arr1.dtype, arr1.size, type(arr1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
arr2.shape, arr2.ndim, arr2.dtype, arr2.size, type(arr2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
arr3.shape, arr3.ndim, arr3.dtype, arr3.size, type(arr3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6

In [12]:
# Create an array of shape (10, 2) with only ones
arr_with_ones = np.ones((10, 2))
arr_with_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
arr_with_zeros = np.zeros((7, 2, 3))
arr_with_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# Create an array within a range of 0 and 100 with step 3
arr4 = np.arange(0,100,3)
arr4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr5 = np.random.randint(10, size=(7, 2))
arr5

array([[9, 0],
       [8, 2],
       [3, 8],
       [3, 7],
       [4, 8],
       [8, 0],
       [3, 2]])

In [22]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr6 = np.random.random((3, 5))
arr6

array([[0.30793165, 0.49262461, 0.42911048, 0.27729732, 0.94981052],
       [0.47235489, 0.08704748, 0.52947422, 0.16307168, 0.18749136],
       [0.82557373, 0.2515093 , 0.08643441, 0.75355223, 0.57379056]])

In [30]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [34]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr7 = np.random.randint(1, 10, size=(3, 7))
arr7
# Find the unique numbers in the array you just created
np.unique(arr7)

array([1, 2, 3, 5, 7, 8, 9])

In [35]:
# Find the 0'th index of the latest array you created
arr7[0]

array([2, 5, 8, 9, 9, 1, 9])

In [36]:
# Get the first 2 rows of latest array you created
arr7[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [38]:
# Get the first 2 values of the first 2 rows of the latest array
arr7[:2, :2]

array([[2, 5],
       [7, 9]])

In [39]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr8 = np.random.randint(10, size=(3, 5))
ones = np.ones((3, 5))

In [45]:
# Add the two arrays together
arr8 + ones

array([[10.,  9.,  7.,  9.,  8.],
       [ 2.,  1.,  7.,  7.,  8.],
       [ 5.,  3.,  8.,  6.,  3.]])

In [57]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
# Try add the array of ones and the other most recent array together
arr8 + ones

# ones = ones.T try this to transponse matrix
# arr8 + ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [61]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3, 5))

In [62]:
# Subtract the new array of ones from the other most recent array
arr8 - ones

array([[ 8.,  7.,  5.,  7.,  6.],
       [ 0., -1.,  5.,  5.,  6.],
       [ 3.,  1.,  6.,  4.,  1.]])

In [63]:
# Multiply the ones array with the latest array
arr8 * ones

array([[9., 8., 6., 8., 7.],
       [1., 0., 6., 6., 7.],
       [4., 2., 7., 5., 2.]])

In [64]:
# Take the latest array to the power of 2 using '**'
arr8 ** 2

array([[81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49],
       [16,  4, 49, 25,  4]])

In [65]:
# Do the same thing with np.square()
np.square(arr8)

array([[81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49],
       [16,  4, 49, 25,  4]])

In [66]:
# Find the mean of the latest array using np.mean()
np.mean(arr8)

5.2

In [67]:
# Find the maximum of the latest array using np.max()
np.max(arr8)

9

In [68]:
# Find the minimum of the latest array using np.min()
np.min(arr8)

0

In [69]:
# Find the standard deviation of the latest array
np.std(arr8)

2.6882460204874605

In [70]:
# Find the variance of the latest array
np.var(arr8)

7.2266666666666675

In [71]:
# Reshape the latest array to (3, 5, 1)
arr8.reshape(3, 5, 1)

array([[[9],
        [8],
        [6],
        [8],
        [7]],

       [[1],
        [0],
        [6],
        [6],
        [7]],

       [[4],
        [2],
        [7],
        [5],
        [2]]])

In [72]:
# Transpose the latest array
arr8.T

array([[9, 1, 4],
       [8, 0, 2],
       [6, 6, 7],
       [8, 6, 5],
       [7, 7, 2]])

What does the transpose do?

In [74]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
m1 = np.random.randint(10, size=(3, 3))
m2 = np.random.randint(10, size=(3, 2))
m1, m2

(array([[3, 3, 4],
        [6, 6, 3],
        [6, 2, 5]]),
 array([[1, 9],
        [8, 4],
        [5, 3]]))

In [77]:
# Perform a dot product on the two newest arrays you created
np.dot(m1, m2)

array([[47, 51],
       [69, 87],
       [47, 77]])

In [81]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
m3 = np.random.randint(10, size=(4, 3))
m4 = np.random.randint(10, size=(4, 3))
m3, m4

(array([[0, 0, 9],
        [3, 6, 1],
        [2, 0, 4],
        [0, 7, 0]]),
 array([[0, 1, 1],
        [5, 6, 4],
        [0, 0, 2],
        [1, 4, 9]]))

In [82]:
# Perform a dot product on the two newest arrays you created
np.dot(m3, m4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [83]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(m3.T, m4)

array([[15, 18, 16],
       [37, 64, 87],
       [ 5, 15, 21]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [84]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
m5 = np.random.randint(10, size=(4, 2))
m6 = np.random.randint(10, size=(4, 2))
m5, m6

(array([[5, 6],
        [3, 6],
        [7, 0],
        [5, 7]]),
 array([[4, 3],
        [1, 5],
        [5, 0],
        [8, 5]]))

In [85]:
# Compare the two arrays with '>'
m5 > m6

array([[ True,  True],
       [ True,  True],
       [ True, False],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [86]:
# Compare the two arrays with '>='
m5 >= m6

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True]])

In [87]:
# Find which elements of the first array are greater than 7
m5 > 7

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [88]:
# Which parts of each array are equal? (try using '==')
m5 == m6

array([[False, False],
       [False, False],
       [False,  True],
       [False, False]])

In [92]:
# Sort one of the arrays you just created in ascending order
np.sort(m5)

array([[5, 6],
       [3, 6],
       [0, 7],
       [5, 7]])

In [99]:
# Sort the indexes of one of the arrays you just created
np.argsort(m6), m6

(array([[1, 0],
        [0, 1],
        [1, 0],
        [1, 0]]),
 array([[4, 3],
        [1, 5],
        [5, 0],
        [8, 5]]))

In [100]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(m6)

6

In [101]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(m6)

5

In [103]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(m6, axis=1), m6

(array([0, 1, 0, 0]),
 array([[4, 3],
        [1, 5],
        [5, 0],
        [8, 5]]))

In [104]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(m6, axis=0), m6

(array([3, 1]),
 array([[4, 3],
        [1, 5],
        [5, 0],
        [8, 5]]))

In [105]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 0.7896728 ,  0.43148946, -1.0967523 , -0.68230156,  0.88751161],
       [ 0.60548313, -0.72029799, -0.26993377, -0.14346223,  0.61700378],
       [ 1.2489407 ,  0.06564916,  1.16920765,  0.87331697,  0.20565013]])

In [121]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10) , np.linspace(1, 100, 16) 



(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]),
 array([  1. ,   7.6,  14.2,  20.8,  27.4,  34. ,  40.6,  47.2,  53.8,
         60.4,  67. ,  73.6,  80.2,  86.8,  93.4, 100. ]))

In [128]:
# Convert images to  numpy array
from matplotlib.image import imread

panda_image = imread("numpy-panda.png")
panda_image.size, panda_image.shape, panda_image.ndim

(24465000, (2330, 3500, 3), 3)